version: '2'
services:
     sip.orchestrator:
        image: ibmcom/voice-gateway-so:latest
        container_name: voice-gateway-so
        ports:
          - "5060:5060"
          - "5060:5060/udp"
        environment:

          - MEDIA_RELAY_HOST=media.relay:8080
          - SIP_HOST=34.245.197.231
          - ENABLE_TRANSCRIPTION_AUDIT_MESSAGES=true
          - MULTI_TENANT_CONFIG_FILE=/vgwConf/tenantConfig.json
          - LOG_LEVEL=all
        volumes:
          - /home/admin/sample.voice.gateway/docker/:/vgwConf/
     media.relay:
        image: ibmcom/voice-gateway-mr:latest
        container_name: voice-gateway-mr
        ports:
          - "16384-16394:16384-16394/udp"
        environment:
          - SDP_ADDRESS=34.245.197.231
          - RTP_UDP_PORT_RANGE=16384-16394
          - MEDIA_RELAY_LOG_LEVEL=DEBUG
          - MEDIA_RELAY_WS_PORT=8080
          - ENABLE_RTCP=true
          - ENABLE_RECORDING=false
        volumes:
          - /usr/src/sample.voice.gateway/docker/recordings:/vgw-media-relay/recordings
