version: '2'
services:
  sip.orchestrator:
    image: ibmcom/voice-gateway-so:latest
    container_name: voice-gateway-so
    ports:
      - "5060:5060"
      - "5060:5060/udp"
    environment:
      # Host name of the CMR.
      - MEDIA_RELAY_HOST=media.relay:8080
      - SIP_HOST=${EXTERNAL_IP}

      # Configure either an SOE or reporting interface to receive the transcriptions (or both)
      # SOE
      # - WATSON_CONVERSATION_APIKEY=XgTrn6CUK4PQscocG51uR2iNcY0B6V9cGv_VKg-Ea4j0
      # - WATSON_CONVERSATION_URL=https://gateway-wdc.watsonplatform.net/assistant/api
       
      # Reporting
      - REPORTING_TRANSCRIPTION_CLOUDANT_URL=https://7c9673c3-6f31-4ee7-b0fa-ee3aa177770d-bluemix.cloudant.com/
      - REPORTING_TRANSCRIPTION_CLOUDANT_APIKEY=7c9673c3-6f31-4ee7-b0fa-ee3aa177770d-bluemix    
      - REPORTING_TRANSCRIPTION_CLOUDANT_DB_NAME=first
      - REPORTING_TRANSCRIPTION_CLOUDANT_EVENT_INDEX=transcription

  media.relay:
    image: ibmcom/voice-gateway-mr:latest
    container_name: voice-gateway-mr
    ports:
      - "16384-16394:16384-16394/udp"
    environment:
      - SDP_ADDRESS=${EXTERNAL_IP}
      - RTP_UDP_PORT_RANGE=16384-16394
      - MEDIA_RELAY_LOG_LEVEL=DEBUG
      - MEDIA_RELAY_WS_PORT=8080

      # Creds for Bluemix STT
      - WATSON_STT_API_KEY=pP4JcyyxahU__SbRt5HSwievzGPt_iYAWcl57PFpi1tU
      - WATSON_STT_URL=https://gateway-wdc.watsonplatform.net/speech-to-text/api



